# Copyright 2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set version = "1.21.0" %}

package:
  name: wayland
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/wayland/wayland/-/archive/{{ version }}/wayland-{{ version }}.tar.bz2
  sha256: e92985abc4eee91b730046a373fdc122c96adb4a3b6757afa07b8a540a8db4fc

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('wayland', max_pin='x') }}

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
  host:
    - expat
    - libffi

test:
  commands:
    - wayland-scanner --help
    - test -f ${PREFIX}/lib/libwayland-egl.so
    - test -f ${PREFIX}/lib/libwayland-client.so
    - test -f ${PREFIX}/lib/libwayland-cursor.so
    - test -f ${PREFIX}/lib/libwayland-server.so
    - test -f ${PREFIX}/lib/pkgconfig/wayland-egl.pc
    - test -f ${PREFIX}/lib/pkgconfig/wayland-client.pc
    - test -f ${PREFIX}/lib/pkgconfig/wayland-cursor.pc
    - test -f ${PREFIX}/lib/pkgconfig/wayland-server.pc
    - test -f ${PREFIX}/include/wayland-egl.h
    - test -f ${PREFIX}/include/wayland-client.h
    - test -f ${PREFIX}/include/wayland-cursor.h
    - test -f ${PREFIX}/include/wayland-server.h

about:
  home: https://gitlab.freedesktop.org/wayland/wayland
  license: MIT
  license_file: COPYING
  summary: Base libraries for the Wayland rendering architecture

extra:
  recipe-maintainers:
    - hmaarrfk
    # - pkgw
